services:

  app:
    build: .
    #image: task-management-system-1.0.0
    restart: always
    container_name: task-management-system-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      JWT_SECRET_PHRASE: ${JWT_SECRET_PHRASE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
    ports:
      - "${APPLICATION_PORT}:8080"
    depends_on:
      - tasks-db


  tasks-db:
    image: postgres:14
    restart: always
    container_name: tasks-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./tasks-system-db-volume:/var/lib/postgresql/data


volumes:
  tasks-system-db-volume: