services:

  app:
    build: .
    restart: always
    container_name: aeris-dvoretsky-container
    environment:
      TELEGRAM_BOT_TOKEN: 7663104943:AAHY3xrVMMcEBJWeeoQ3YefmvchTK1sPmIU
      TELEGRAM_BOT_USERNAME: aeris_dvorestsky_bot

      OPENAI_API_KEY: mocked-api-key
      OPENAI_API_ENDPOINT: https://api.openai.com/v1/chat/completions

      DATABASE_URL: jdbc:postgresql://tasks-db:5432/aerisdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

      POSTGRES_DB: aerisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

      SPRING_DATASOURCE_URL: jdbc:postgresql://tasks-db:5432/aerisdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

    ports:
      - "${APPLICATION_PORT}:8080"
    depends_on:
      - tasks-db
      - redis

  tasks-db:
    image: postgres:14
    restart: always
    container_name: aeris-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: aerisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./aeris-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    container_name: aeris-redis
    ports:
      - "6379:6379"

volumes:
  aeris-db-volume: