spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml  # Путь к вашему changelog
  datasource:
    url: ${DB_URL}  # Переменная окружения для URL базы данных
    username: ${DB_USERNAME}  # Переменная окружения для имени пользователя
    password: ${DB_PASSWORD}  # Переменная окружения для пароля
  logging:
    level:
      root: INFO  # Уровень логирования по умолчанию
      com.aeris.bot: DEBUG  # Уровень логирования для вашего пакета
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

bot:
  username: ${TELEGRAM_BOT_USERNAME}  # Имя бота для Telegram
  token: ${TELEGRAM_BOT_TOKEN}  # Токен вашего бота

openai:
  api-key: ${OPENAI_API_KEY}  # Используем переменную из .env для API-ключа
  endpoint: ${OPENAI_API_ENDPOINT}  # Эндпоинт для общения с OpenAI API

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Открыть все эндпоинты для мониторинга
  metrics:
    export:
      prometheus:
        enabled: true  # Включаем экспорт метрик в Prometheus
