spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml  # Путь к вашему changelog
  datasource:
    url: jdbc:postgresql://db:5432/aerisdb
    username: postgres
    password: password # Переменная окружения для пароля
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
     hibernate:
        format_sql: true
  logging:
    level:
      root: INFO  # Уровень логирования по умолчанию
      com.aeris.bot: DEBUG  # Уровень логирования для вашего пакета
  data:
    redis:
      host: localhost
      port: 6379

bot:
  username: aeris_dvorestsky_bot  # Имя бота для Telegram
  token: 7663104943:AAHY3xrVMMcEBJWeeoQ3YefmvchTK1sPmIU # Токен вашего бота

openai:
  api-key: ${OPENAI_API_KEY}  # Используем переменную из .env для API-ключа
  endpoint: ${OPENAI_API_ENDPOINT}  # Эндпоинт для общения с OpenAI API

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Открыть все эндпоинты для мониторинга
  metrics:
    export:
      prometheus:
        enabled: true  # Включаем экспорт метрик в Prometheus
hostess:
  chat:
    id=123456789: