version: '3.8'
services:
  aeris-bot:
    build: .
    container_name: aeris_bot
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: aerisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"