telegram:
  bot:
    username: "AerisBot"
    token: "ВАШ_ТОКЕН"
  openai:
    api-key: "ВАШ_API_КЛЮЧ"
    endpoint: "https://api.openai.com/v1/chat/completions"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aerisdb
    username: postgres
    password: password
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    com.aeris.bot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true